In [ ]:
pip install pandas numpy joblib scikit-learn

# Emotion Model Training

In [ ]:
#####       Using Logistic Regression       #####

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# -----------------------------
# 1. Load Dataset
# -----------------------------
data = pd.read_csv("combined_emotion_dataset.csv")

X = data["text"]
y = data["emotion"]

# -----------------------------
# 2. Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# -----------------------------
# 3. TF-IDF Vectorization
# -----------------------------
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# -----------------------------
# 4. Train Logistic Regression
# -----------------------------
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

model.fit(X_train_tfidf, y_train)

# -----------------------------
# 5. Evaluation
# -----------------------------
y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

# -----------------------------
# 6. Save Model + Vectorizer
# -----------------------------
joblib.dump(model, "emotion_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("\nModel and vectorizer saved successfully.")

Accuracy: 0.6244897959183674

Classification Report:

              precision    recall  f1-score   support

       anger       0.42      0.49      0.45       140
  comparison       0.96      0.96      0.96       140
   confusion       0.47      0.44      0.45       140
        fear       0.56      0.50      0.53       140
    pressure       0.96      0.98      0.97       140
     sadness       0.44      0.44      0.44       140
  self_doubt       0.57      0.56      0.57       140

    accuracy                           0.62       980
   macro avg       0.63      0.62      0.62       980
weighted avg       0.63      0.62      0.62       980


Confusion Matrix:

[[ 68   0  16  10   0  28  18]
 [  0 135   0   0   2   2   1]
 [ 19   1  61  16   0  26  17]
 [ 29   0  13  70   2  15  11]
 [  0   2   0   1 137   0   0]
 [ 26   2  21  16   0  62  13]
 [ 20   1  18  12   1   9  79]]

Model and vectorizer saved successfully.


In [ ]:
#####         Using Support Vector Machine          #####

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.svm import LinearSVC

# -----------------------------
# 1. Load Dataset
# -----------------------------
data = pd.read_csv("combined_emotion_dataset.csv")

X = data["text"]
y = data["emotion"]

# -----------------------------
# 2. Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# -----------------------------
# 3. TF-IDF Vectorization
# -----------------------------
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# -----------------------------
# 4. Support Vector Machine
# -----------------------------
model = LinearSVC(class_weight="balanced")

model.fit(X_train_tfidf, y_train)

# -----------------------------
# 5. Evaluation
# -----------------------------
y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

# -----------------------------
# 6. Save Model + Vectorizer
# -----------------------------
joblib.dump(model, "emotion_model_svm.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer_svm.pkl")

print("\nModel and vectorizer saved successfully.")

Accuracy: 0.6306122448979592

Classification Report:

              precision    recall  f1-score   support

       anger       0.46      0.49      0.47       140
  comparison       0.96      0.97      0.96       140
   confusion       0.46      0.45      0.45       140
        fear       0.55      0.55      0.55       140
    pressure       0.96      0.98      0.97       140
     sadness       0.46      0.44      0.45       140
  self_doubt       0.56      0.53      0.54       140

    accuracy                           0.63       980
   macro avg       0.63      0.63      0.63       980
weighted avg       0.63      0.63      0.63       980


Confusion Matrix:

[[ 69   1  18   7   0  24  21]
 [  0 136   0   0   1   3   0]
 [ 17   2  63  23   0  19  16]
 [ 25   0  11  77   2  15  10]
 [  0   1   0   2 137   0   0]
 [ 20   2  24  17   3  62  12]
 [ 20   0  22  13   0  11  74]]

Model and vectorizer saved successfully.


# Context Model Training

In [ ]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# -----------------------------
# 1. Load Dataset
# -----------------------------
data = pd.read_csv("context_dataset_final.csv")

X = data["text"]
y = data["context"]

# -----------------------------
# 2. Train-Test Split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# -----------------------------
# 3. TF-IDF Vectorization
# -----------------------------
vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# -----------------------------
# 4. Train Linear SVM
# -----------------------------
model = LinearSVC(class_weight="balanced")

model.fit(X_train_tfidf, y_train)

# -----------------------------
# 5. Evaluation
# -----------------------------
y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

# -----------------------------
# 6. Save Model
# -----------------------------
joblib.dump(model, "context_model.pkl")
joblib.dump(vectorizer, "context_vectorizer.pkl")

print("\nContext model and vectorizer saved successfully.")

Accuracy: 0.9559471365638766

Classification Report:

               precision    recall  f1-score   support

    academics       0.95      0.97      0.96        40
       family       0.95      0.97      0.96        40
future_career       0.98      0.96      0.97        51
peer_pressure       0.95      0.98      0.96        56
self_identity       0.95      0.88      0.91        40

     accuracy                           0.96       227
    macro avg       0.96      0.95      0.95       227
 weighted avg       0.96      0.96      0.96       227


Confusion Matrix:

[[39  0  0  0  1]
 [ 0 39  0  1  0]
 [ 0  1 49  0  1]
 [ 1  0  0 55  0]
 [ 1  1  1  2 35]]

Context model and vectorizer saved successfully.


# Gita RAG pipeling

In [ ]:
# Convert Verses to Embeddings

!pip install sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 43.0 MB/s eta 0:00:00


In [ ]:
#  Prepare the Gita Dataset

import pandas as pd

# Load dataset
df = pd.read_csv("gita_dataset.csv")

# Remove rows with missing meanings
df = df.dropna(subset=["meaning"])

# Clean text
df["meaning"] = df["meaning"].str.lower().str.strip()

# Reset index
df = df.reset_index(drop=True)

print("Total verses:", len(df))

# Save cleaned dataset
df.to_csv("gita_cleaned.csv", index=False)

print("Cleaned dataset saved.")

Total verses: 637
Cleaned dataset saved.


In [ ]:
# now genrating the embeddings

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

# Load cleaned dataset
df = pd.read_csv("gita_cleaned.csv")

# texts = df["meaning"].tolist()
texts = (df["text"] + " " + df["meaning"]).tolist()

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Generate embeddings
embeddings = model.encode(texts, show_progress_bar=True)

# Save embeddings
np.save("gita_embeddings.npy", embeddings)

print("Embeddings saved successfully.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


Batches:   0%|          | 0/20 [00:00<?, ?it/s]

Embeddings saved successfully.


In [ ]:
# Build the FAISS Vector Index

import numpy as np
import faiss

# Load embeddings
embeddings = np.load("gita_embeddings.npy")

dimension = embeddings.shape[1]

# Create FAISS index
index = faiss.IndexFlatL2(dimension)

# Add embeddings
index.add(embeddings)

# Save index
faiss.write_index(index, "gita_index.faiss")

print("Vector index built successfully.")

Vector index built successfully.


In [ ]:
# loading everything
import pandas as pd
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

# Load dataset
df = pd.read_csv("gita_cleaned.csv")

# Load FAISS index
index = faiss.read_index("gita_index.faiss")

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
CONCEPT_MAP = {
    "pressure": [
        "duty without attachment to results",
        "focus on action",
        "calmness under pressure",
        "discipline of the mind"
    ],

    "fear": [
        "removal of fear",
        "inner strength",
        "steadiness of mind"
    ],

    "self_doubt": [
        "self knowledge",
        "confidence in duty",
        "removal of ignorance"
    ],

    "comparison": [
        "detachment from outcomes",
        "equanimity in success and failure"
    ]
}
def build_query(user_text, emotion, context):

    concepts = CONCEPT_MAP.get(emotion, [])

    concept_text = " ".join(concepts)

    query = f"""
Student problem: {user_text}

Emotion: {emotion}
Context: {context}

Relevant philosophical themes:
{concept_text}

Teachings from Bhagavad Gita about duty, calmness, discipline and balance.
"""

    return query.strip()

In [ ]:
def embed_query(query):

    query_vector = model.encode([query])

    return query_vector

In [ ]:
from sentence_transformers import CrossEncoder

reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def search_index(query_vector, k):
    distances, indices = index.search(query_vector, k)
    return indices[0]

def rerank_results(query, candidate_indices):

    candidates = df.iloc[candidate_indices]

    pairs = []

    for _, row in candidates.iterrows():
        text = row["text"] + " " + row["meaning"]
        pairs.append((query, text))

    scores = reranker.predict(pairs)

    candidates = candidates.copy()
    candidates["score"] = scores

    ranked = candidates.sort_values("score", ascending=False)

    return ranked.head(3)

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  | 
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [ ]:
# def get_verses(indices):

#     results = df.iloc[indices]

#     verses = []

#     for _, row in results.iterrows():

#         verses.append({
#             "chapter": row["chapter"],
#             "verse": row["verse"],
#             "text": row["text"],
#             "meaning": row["meaning"]
#         })

#     return verses

In [ ]:

def retrieve_relevant_verses(user_text, emotion, context):

    query = build_query(user_text, emotion, context)

    query_vector = embed_query(query)

    candidate_indices = search_index(query_vector, k=50)

    ranked = rerank_results(query, candidate_indices)

    return ranked

In [ ]:
if __name__ == "__main__":

    user_text = "I feel pressure because exams are coming"

    emotion = "pressure"

    context = "academics"

    results = retrieve_relevant_verses(user_text, emotion, context)

    for index, r in results.iterrows():

        print("\nChapter:", r["chapter"], "Verse:", r["verse"])
        print("Text:", r["text"])
        print("Meaning:", r["meaning"])

AttributeError: 'int' object has no attribute 'search'

In [ ]:
!pip install groq 

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.7/139.7 kB 5.9 MB/s eta 0:00:00


In [ ]:
from groq import Groq

client = Groq(api_key="YOUR API KEY")

In [ ]:
def build_verse_context(verses):

    context = ""

    for index, v in verses.iterrows():
        context += f"""
Chapter {v['chapter']} Verse {v['verse']}:
{v['text']}
Meaning: {v['meaning']}
"""

    return context

In [ ]:
# def build_prompt(user_text, emotion, context, verse_context):

#     prompt = f"""
# A teenager is facing the following situation.

# User Situation:
# {user_text}

# Detected Emotion:
# {emotion}

# Life Context:
# {context}

# Relevant Bhagavad Gita verses:
# {verse_context}


# Your role is to interpret these verses and provide guidance using THREE perspectives.

# Important Rules:
# - Use ONLY the verses provided above.
# - Do NOT introduce or quote any other verses.
# - Do NOT invent teachings.
# - Ground every idea in the provided verses.
# - Avoid generic therapy language.
# - Be concise and thoughtful.


# Provide the response in the following structure:


# 1. Emotional Perspective
# - Acknowledge the person's feelings.
# - Briefly relate the emotional struggle to a similar state described in the provided verses.
# - Do not exaggerate sympathy or use filler phrases.


# 2. Strategic Perspective
# - Extract a practical mindset or approach suggested by the teachings.
# - Explain how the person can think or act differently in this situation.
# - Focus on clarity, discipline, or perspective.


# 3. Spiritual Perspective
# - Explain the deeper philosophical insight from the Bhagavad Gita.
# - Focus on the underlying principle behind the verses.
# - Keep the explanation reflective and meaningful.


# Tone Guidelines:
# - calm
# - wise
# - reflective
# - mentor-like guidance to a student

# Avoid:
# - religious preaching
# - motivational clichés
# - dramatic emotional language
# """

#     return prompt

def build_prompt(user_text, emotion, context, verse_context):

    prompt = f"""
A teenager is facing the following situation.

User Situation:
{user_text}

Detected Emotion:
{emotion}

Life Context:
{context}

Relevant Bhagavad Gita verses:
{verse_context}


Your task is to interpret ONLY the teachings listed above.

STRICT RULES:
- Use only the verses provided in "Relevant Bhagavad Gita verses".
- Do NOT mention or quote any other Bhagavad Gita verse.
- Do NOT rely on outside knowledge.
- If a verse is not in the list, ignore it completely.
- When referencing a teaching, explicitly cite the verse number from the provided list.


Provide guidance using THREE perspectives:

1. Emotional Perspective
- Briefly acknowledge the feeling.
- If relevant, relate the emotional state to a verse from the provided list.


2. Strategic Perspective
- Extract a practical mindset or approach from the provided verses.
- Explain how the person can think or act in this situation.


3. Spiritual Perspective
- Explain the deeper philosophical insight contained in the provided verses.
- Focus on the underlying principle.


Tone:
- calm
- thoughtful
- mentor-like
- grounded in the verses

Avoid:
- motivational clichés
- exaggerated sympathy
- religious preaching
- mentioning verses not provided in the context
"""
    return prompt

In [ ]:
def generate_perspectives(user_text, emotion, context, verses):

    verse_context = build_verse_context(verses)

    prompt = build_prompt(user_text, emotion, context, verse_context)

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are Krishna's Lens, a reflective guide inspired by Bhagavad Gita wisdom."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.6
    )

    return response.choices[0].message.content

In [ ]:
if __name__ == "__main__":

    user_text = "“I just went through a breakup and I feel empty. I keep thinking about what I did wrong and I can’t focus on anything."

    emotion = "sadness"

    context = "self_identity"

    verses = retrieve_relevant_verses(user_text, emotion, context)

    output = generate_perspectives(user_text, emotion, context, verses)

    print(output)

My young friend, I can sense the depth of your sadness. It's natural to feel empty and overwhelmed after a breakup. 

**Emotional Perspective**
Your feelings are valid, and it's essential to acknowledge them. As described in Chapter 1 Verse 29, it's common to experience physical and emotional distress when we're overcome with grief. Your body and mind are reacting to the pain, and it's okay to feel this way.

**Strategic Perspective**
In this situation, it's crucial to find a way to navigate your emotions and thoughts. As mentioned in Chapter 2 Verse 7, it's normal to feel torn between your emotions and a sense of duty or responsibility. You might be wondering what to do next or how to move forward. Take a step back, and ask yourself what you need to do to take care of yourself. Seek guidance from within, just as Arjuna sought guidance from his mentor. Consider what small steps you can take each day to regain your focus and sense of purpose.

**Spiritual Perspective**
As we reflect on 